import Head from 'next/head';
import Home from '@/components/screens/Home/Home';
import Cursor from '@/components/Cursor/Cursor';
import Contaier from '@/components/screens/Container/Container';
import Header from '@/components/Header/Header';
import About from '@/components/screens/About/About';
import Resume from '@/components/screens/Resume/Resume';
import Main from '@/components/screens/Main/Main';
import Footer from '@/components/Footer/Footer';
import { useRouter } from 'next/router';
import Background from '@/components/Background/Background';
import dynamic from 'next/dynamic';
import { useEffect, useRef, useState } from 'react';
import { useInView } from 'react-intersection-observer';
import Portfolio from '@/components/screens/Portfolio/Portfollio';

export default function HomePage() {
  const { asPath } = useRouter();
  const [activeUrl, setActiveUrl] = useState<string>('/');
  const [innerWidth, setInnerWidth] = useState<number>(1920);

  const observerRef = useRef<HTMLDivElement | null>(null);

  const { ref, inView, entry } = useInView({
    /* Optional options */
    threshold: 0,
  });

  useEffect(() => {
    setActiveUrl(asPath);
  }, [asPath]);

  useEffect(() => {
    window.scroll({
      behavior: 'smooth',
    });

    window.addEventListener('resize', displayWindowSize);

    function displayWindowSize() {
      setInnerWidth(window.innerWidth);
    }

    displayWindowSize();

    return () => {
      window.removeEventListener('resize', displayWindowSize);
    };
  }, []);

  //   useEffect(() => {
  // // Создаем новый observer (наблюдатель)
  // let observer = new IntersectionObserver(function (entries) {
  //   entries.forEach(function (entry) {
  //       // Выводим в консоль сам элемент
  //       console.log(entry.target);
  //       // Выводим в консоль true (если элемент виден) или false (если нет)
  //       console.log(entry.isIntersecting);
  //   });
  // });

  // // Задаем элемент для наблюдения
  // //let el = document.querySelector('.element');

  // // Прикрепляем его к «наблюдателю»
  // observer.observe(observerRef.current);
  //   }, []);

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cursor />

      <Contaier>
        <Header />
        <main className="main">
          <Home />
          <div style={{ height: '100%', width: '100%', position: 'relative' }}>
            <About
              id={innerWidth < 1200 ? 'about' : ''}
              className={`page ${activeUrl === '/' ? 'active' : ''}`}
            />
            <Resume
              id={innerWidth < 1200 ? 'resume' : ''}
              className={`page ${activeUrl === '/#resume' ? 'active' : ''}`}
            />

            <Portfolio
              id={innerWidth < 1200 ? 'portfolio' : ''}
              className={`page ${activeUrl === '/#portfolio' ? 'active' : ''}`}
            />
          </div>
        </main>
      </Contaier>
      <Footer />

      <Background />
    </>
  );
}
