import Head from 'next/head';
import Home from '@/components/screens/Home/Home';
import Cursor from '@/components/Cursor/Cursor';
import Contaier from '@/components/screens/Container/Container';
import Header from '@/components/Header/Header';
import About from '@/components/screens/About/About';
import Resume from '@/components/screens/Resume/Resume';
import Footer from '@/components/Footer/Footer';
import { useRouter } from 'next/router';
import Background from '@/components/Background/Background';
import { useEffect, useRef, useState } from 'react';
import { useInView } from 'react-intersection-observer';
import Portfolio from '@/components/screens/Portfolio/Portfollio';

export default function HomePage() {
  const { asPath } = useRouter();
  const [activeUrl, setActiveUrl] = useState<string>('/');
  const [innerWidth, setInnerWidth] = useState<number>(1920);

  const observerRef = useRef<HTMLDivElement | null>(null);

  const ref1 = useRef(null)

  const { ref, inView, entry } = useInView({
    threshold: 0,
  });

  useEffect(() => {
    setActiveUrl(asPath);
  }, [asPath]);

  useEffect(() => {


    window.addEventListener('resize', displayWindowSize);

    function displayWindowSize() {
      setInnerWidth(window.innerWidth);
    }

    displayWindowSize();

    return () => {
      window.removeEventListener('resize', displayWindowSize);
    };
  }, []);


  const buttonHandler = (ref) => {
    ref.current.scrollIntoView();
  };


  return (
    <>
      <Head>
        <title>Frontend-разработчик | Кочнев Антон</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cursor />

      <Contaier>
        <Header />
        <main className="main">
          <Home />

          <button onClick={() => buttonHandler(ref1)}>Go to 1</button>
          <div style={{ height: '100%', width: '100%', position: 'relative' }}>
            <About
              id={innerWidth < 1200 ? 'about' : ''}
              className={`page ${activeUrl === '/' ? 'active' : ''}`}
            />
            <Resume
              id={innerWidth < 1200 ? 'resume1' : ''}
              className={`page ${activeUrl === '/#resume' ? 'active' : ''}`}
            />

            <Portfolio
           
           
              id={innerWidth < 1200 ? 'portfolio' : ''}
              className={`page ${activeUrl === '/#portfolio' ? 'active' : ''}`}
            />

            <div ref={ref1}>
              123123
            </div>
          </div>
        </main>
      </Contaier>
      <Footer />

      <Background />
    </>
  );
}
