import Head from 'next/head';
import Cursor from '@/components/Cursor/Cursor';
import Background from '@/components/Background/Background';
import PortfolioList from '@/components/screens/Portfolio/PortfolioList';
import PageItem from '@/components/PageItem/PageItem';
import Link from 'next/link';
import Layout from '@/components/Layouts/LayoutMain/Layout';

export default function PortfolioPage() {
  return (
    <>
      <Head>
        <title>Портфолио | Кочнев Антон</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cursor />

      <Layout>
        <Link style={{zIndex: '2', position: 'relative'}} href='/'>Назад</Link>
        <PageItem className="portfolio_section" title="Портфолио">
          <PortfolioList />
        </PageItem>
      </Layout>

      <Background />
    </>
  );
}
